name: build
on: [push]
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up docker
        uses: docker/setup-buildx-action@v3
      - name: Docker build
        run: docker build -t java-spring:latest initial/
